package cn.spacexc.wearbili.dataclass.videoDetail

data class Data(
    val activity_url: String,
    val aid: Long,
    val bvid: String,
    val cid: Long,
    val cm_config: CmConfig,
    val cms: List<Cm>,
    val config: Config,
    val copyright: Int,
    val ctime: Int,
    val desc: String,
    val dimension: Dimension,
    val dislike_reasons: List<DislikeReason>,
    val dislike_reasons_v2: DislikeReasonsV2,
    val dm_seg: Int,
    val duration: Int,
    val `dynamic`: String,
    val elec: Elec,
    val first_frame: String,
    val history: History?,
    val label: Label,
    val like_custom: LikeCustom,
    val mission_id: Long,
    val owner: Owner,
    val owner_ext: OwnerExt,
    val pages: List<Page>,
    val pic: String,
    val play_param: Int,
    val premiere_resource: Any,
    val pub_location: String,
    val pubdate: Long,
    val relates: List<Relate>,
    val req_user: ReqUser,
    val rights: Rights,
    val season: Season?,
    val share_subtitle: String,
    val short_link: String,
    val short_link_v2: String,
    val stat: StatX,
    val state: Int,
    val t_icon: TIcon,
    val tag: List<Tag>,
    val tid: Long,
    val title: String,
    val tname: String,
    val videos: Int,
    val staff: List<Staff>?,
    val honor: Honor?
) {
    data class Pages(val pages: List<Page>)
}