package cn.spacexc.wearbili.dataclass.video.rcmd

data class Item(
    val ad_info: AdInfo?,
    val args: Args,
    val can_play: Int,
    val card_goto: String,
    val card_type: String,
    val cover: String,
    val cover_left_1_content_description: String,
    val cover_left_2_content_description: String,
    val cover_left_icon_1: Int,
    val cover_left_icon_2: Int,
    val cover_left_text_1: String,
    val cover_left_text_2: String,
    val cover_right_content_description: String,
    val cover_right_text: String,
    val desc: String?,
    val desc_button: DescButton?,
    val goto: String,
    val goto_icon: GotoIcon?,
    val idx: Int,
    val official_icon: Int?,
    val `param`: String,
    val player_args: PlayerArgs,
    val rcmd_reason: String?,
    val rcmd_reason_style: RcmdReasonStyle?,
    val talk_back: String?,
    val three_point: ThreePoint,
    val three_point_v2: List<ThreePointV2>,
    val title: String,
    val track_id: String,
    val uri: String,
    val badge: String?
)