package cn.spacexc.wearbili.dataclass.videoDetail.web

data class Data(
    val aid: Long,
    val bvid: String,
    val cid: Long,
    val copyright: Int,
    val ctime: Int,
    val desc: String,
    val desc_v2: List<DescV2>,
    val dimension: Dimension,
    val duration: Int,
    val `dynamic`: String,
    val honor_reply: HonorReply,
    val is_chargeable_season: Boolean,
    val is_season_display: Boolean,
    val is_story: Boolean,
    val like_icon: String,
    val need_jump_bv: Boolean,
    val no_cache: Boolean,
    val owner: Owner,
    val staff: List<cn.spacexc.wearbili.dataclass.videoDetail.web.Staff>,
    val pages: List<Page>,
    val pic: String,
    val premiere: Any,
    val pubdate: Long,
    val redirect_url: String,
    val rights: Rights,
    val stat: Stat,
    val state: Int,
    val subtitle: Subtitle,
    val teenage_mode: Int,
    val tid: Long,
    val title: String,
    val tname: String,
    val user_garb: UserGarb,
    val videos: Int,
)