name: Build CI

on:
  release:
    types: [published]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          echo ${{ secrets.SIGN_KEY }} | base64 -d > app.jks
          git submodule update --init --recursive
          ./gradlew :app:assembleDebug
        env:
          KEYSTORE_PATH: "./app.jks"
          KEYSTORE_PASSWORD: ${{ secrets.SIGN_PASS }}
          KEY_ALIAS: ${{ secrets.SIGN_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ALIA_PASS }}
          CommitNumber: ${{ github.run_number }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        if: ${{ !github.event.pull_request }}
        with:
          path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
          name: ChatWithMe
          
